HangfireEmployee/Models/AddEmployeeDto.cs
namespace HangfireEmployee.Models
{
    public class AddEmployeeDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

HangfireEmployee/Models/EmployeeDto.cs
namespace HangfireEmployee.Models
{
    public class EmployeeDto
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

HangfireEmployee/Models/ErrorViewModel.cs
using System;

namespace HangfireEmployee.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HangfireEmployee/Models/EventDto.cs
namespace HangfireEmployee.Models
{
    public class EventDto
    {
        public int Id { get; set; }
        public string Description { get; set; }
    }
}

HangfireEmployee/Controllers/EmployeeController.cs
namespace HangfireEmployee.Controllers
{
    using DAL.Repository;
    using Microsoft.AspNetCore.Mvc;
    using HangfireEmployee.Models;
    using DAL.Models;
    using System.Collections.Generic;
    using Hangfire;

    public class EmployeeController : Controller
    {
        private readonly EmployeeRepository EmployeeRepository;
        private readonly EventRepository EventRepository;
        public EmployeeController()
        {
            EmployeeRepository = new EmployeeRepository();
            EventRepository = new EventRepository();
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetEmployees()
        {
            var employeeList = EmployeeRepository?.GetEmployees();
            var employeeDtoList = new List<EmployeeDto>();
            foreach(var employee in employeeList)
            {
                var employeeDto = new EmployeeDto()
                {
                    Id = employee.Id,
                    Name = employee.Name
                };
                employeeDtoList.Add(employeeDto);
            }
            return View(employeeDtoList);
        }


        [HttpGet]
        public ActionResult Create()
        {
            var addEmployeeDto = new AddEmployeeDto();
            return View(addEmployeeDto);
        }

        [HttpPost]
        public ActionResult Create(AddEmployeeDto addEmployeeDto)
        {
            Employee employee = new Employee()
            {
                Name= addEmployeeDto.Name
            };

            EmployeeRepository.AddEmployee(employee);
            BackgroundJob.Enqueue(() => AddNewEvent(employee.Name));
            return Redirect("/");
        }

        public void AddNewEvent(string employeeName)
        {
            string eventDescription = employeeName + "Added";
            Event @event = new Event()
            {
                EventDescription = eventDescription
            };
            EventRepository.AddEvent(@event);
        }


    }
}

HangfireEmployee/Controllers/EventController.cs
namespace HangfireEmployee.Controllers
{
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Mvc;

    using DAL.Repository;
    using HangfireEmployee.Models;

    public class EventController : Controller
    {

        private readonly EventRepository EventRepository;
        public EventController()
        {
            EventRepository = new EventRepository();
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult GetEvents()
        {
            var eventList = EventRepository?.GetEvents();
            var eventDtoList = new List<EventDto>();
            foreach (var @event in eventList)
            {
                var eventDto = new EventDto()
                {
                    Id = @event.Id,
                    Description = @event.EventDescription
                };
                eventDtoList.Add(eventDto);
            }
            return View(eventDtoList);
        }
    }
}

HangfireEmployee/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HangfireEmployee.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

HangfireEmployee/Views/Employee/Create.cshtml
@model HangfireEmployee.Models.AddEmployeeDto

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>EmployeeDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

HangfireEmployee/Views/Employee/GetEmployees.cshtml
@model IEnumerable<HangfireEmployee.Models.EmployeeDto>

@{
    ViewData["Title"] = "GetEmployees";
}

<h2>GetEmployees</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
        </tr>
}
    </tbody>
</table>

HangfireEmployee/Views/Event/GetEvents.cshtml
@model IEnumerable<HangfireEmployee.Models.EventDto>

@{
    ViewData["Title"] = "GetEvents";
}

<h2>GetEvents</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        </tr>
}
    </tbody>
</table>

HangfireEmployee/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

HangfireEmployee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HangfireEmployee</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HangfireEmployee</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Employee" asp-action="Create">Create Employee</a></li>
                    <li><a asp-area="" asp-controller="Employee" asp-action="GetEmployees">Employee List</a></li>
                    <li><a asp-area="" asp-controller="Event" asp-action="GetEvents">Event List</a></li>
                    <li><a href="/hangfire"><span>Hangfire</span></a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - HangfireEmployee</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>